version: "3"

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: app42
      MYSQL_DATABASE: db
      MYSQL_USER: app42
      MYSQL_PASSWORD: app42
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
    networks:
      - backend

  maven:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend

      
networks:
  backend: