version: "3"

services:

  maven:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: app42
      MYSQL_DATABASE: db
      MYSQL_USER: app42
      MYSQL_PASSWORD: app42
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 5
    ports:
      - "8514:8514"
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
    networks:
      - backend
      
networks:
  backend: